name: Offer Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review-offer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Extract Offer Amount
        id: extract_offer
        run: |
          if [[ -f offer.txt ]]; then
            AMOUNT=$(grep -o '\$[0-9]*' offer.txt | tr -d '$')
            echo "Offer: $AMOUNT"
          else
            echo "offer.txt not found."
            echo "amount=" >> $GITHUB_OUTPUT
          fi

      - name: Review the Offer
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const amount = parseInt('${{ steps.extract_offer.outputs.amount }}');
            const isValid = !isNaN(amount) && amount >= 0 && amount <= 100;

            let message;
            if (!isValid) {
              message = "⚠️ Invalid offer: Please offer a dollar amount between $0 and $100.";
            } else if (amount >= 30) {
              message = "✅ Accept: This is a fair offer.";
            } else {
              message = "❌ Reject: This offer is too low.";
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
